import type { Metadata } from "next";
import "@/styles/globals.css";
import NavBar from "@/components/NavBar/NavBar";
import { inter } from "@/services/fonts";
import React from "react";
import { ToastProvider } from "@/components/Ui/ToastContext";
import { RoleCheckProvider } from "@/providers/RoleCheckProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  {
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>
) {
  return (
    <html lang="es">
      <body className={`${inter.className}`}>
        <RoleCheckProvider>
          <ToastProvider>{children}</ToastProvider>
        </RoleCheckProvider>
      </body>
    </html>
  );
}
