import type { Metadata } from "next";
import SideNav from "@/components/SideNav/SideNav";

export const metadata: Metadata = {
  title: "Admin Page",
  description: "Generated by create next app",
};

export default function AdminLayout(
  {
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
  return (
    <div className={`horizontal-flex`}>
      <div className="side-nav">
        <SideNav />
      </div>
      <div className="content">
        {children}
      </div>
    </div>
  );
}
