// Importamos el tipo Metadata desde Next.js para definir los metadatos de la página.
import type { Metadata } from "next";

// Importamos los estilos globales de la aplicación.
import "@/styles/globals.css";

// Importamos los componentes NavBar y Footer.
import NavBar from "@/components/NavBar/NavBar";
import { inter } from "@/services/fonts"; // Aunque se importa, la variable `inter` no se usa en el código.
import Footer from "./components/Footer";

// Definimos los metadatos de la aplicación, como el título y la descripción.
export const metadata: Metadata = {
    title: "TechShare",
    description: "Generated by create next app",
};

// Definimos el componente RootLayout, que servirá como estructura base para la aplicación.
export default function RootLayout(
    {
        children, // `children` representa los componentes hijos que se renderizarán dentro del layout.
    }: Readonly<{ 
        children: React.ReactNode; // Asegura que `children` sea un nodo de React y no se modifique.
    }>
) {
    return (
        // Contenedor principal que ocupa toda la pantalla, con flexbox para organizar los elementos.
        <div className="h-screen flex flex-col justify-between overflow-y-scroll scrollbar-hide">
            
            {/* Contenedor para la barra de navegación y el contenido principal */}
            <div className="m-8">
                <NavBar /> {/* Barra de navegación */}
                
                {/* Contenedor para el contenido de la página con margen superior, bordes redondeados y sombra */}
                <div className="mt-8 rounded-lg shadow-black/20 shadow-lg">
                    {children} {/* Aquí se renderizan las páginas de la aplicación */}
                </div>
            </div>

            <Footer /> {/* Pie de página */}
        </div>
    );
}

