import type { Metadata } from "next";
import "@/styles/globals.css";
import NavBar from "@/components/NavBar/NavBar";
import { inter } from "@/services/fonts"
import Footer from "./components/Footer";

export const metadata: Metadata = {
    title: "TechShare",
    description: "Generated by create next app",
};

export default function RootLayout(
    {
        children,
    }: Readonly<{
        children: React.ReactNode;
    }>) {
    return (
        <div>
            <div className="m-8">
                <NavBar />
                <main className="mt-8 rounded-lg shadow-black/20 shadow-lg">
                    {children}
                </main>
            </div>
            <Footer />
        </div>
    );
}
